
spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        acknowledge-mode: manual
    #确认消息已发送到交换机(Exchange) 使用启用消息确认模式
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    #当mandatory标志位设置为true时，如果exchange根据自身类型和消息routingKey无法找到一个合适的queue存储消息，
    #那么broker会调用basic.return方法将消息返还给生产者;当mandatory设置为false时，出现上述情况broker会直接将消息丢弃;
    #通俗的讲，mandatory标志告诉broker代理服务器至少将消息route到一个队列中，否则就将消息return给发送者
    template:
      mandatory: true



server:
  port: 8081
